### PR TITLE
Homepage & Product Page

### PR DESCRIPTION
**Pull request by percius47**
Added:
- global nav
- homepage
- home categories
- product page
 - product grid
 - product cards
 - card fields
 -filters
- universal footer

Check out Homepage at:  [Home](https://adoring-mclean-126a96.netlify.app/pages/home.html)
Check out Product page at: [Product](https://adoring-mclean-126a96.netlify.app/pages/product-page.html)
All/Any feedback is valuable.

### CODE REVIEW

**Review by tanveertkd — APPROVED** [review]
You might want to adjust the spacing on your navigation bar. The login, account and cart buttons seem to be too spaced out. Additionally, the two cards on your homepage are overlapping the footer, so you might want to take a look at that as well. I'm assuming that you're going to make the site responsive later on.
Apart from that this is good to go!

**Review by someshtiwarii — APPROVED** [review]
apart from what Tanveer said, rest looks good to go

**Review by adidoshi — COMMENTED** [review]
Just a suggestion, in your `.header-wrapper` if you give height: auto then it gets properly aligned.

**Review by adidoshi — APPROVED** [review]
Rest looks good, specially the image hover on products page!

**Pull request merged**
